spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Server settings
server:
  port: ${SERVER_PORT}

bezkoder:
  app:
    jwtSecret: ${JWT_SECRET_KEY}
    jwtExpirationMs: 86400000

# Print properties at runtime for debugging
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer: debug